export const color = {
  PRIMARY_COLOR: '#FFC107',
  SECONDARY_COLOR: '#555',
  SUCCESS_COLOR: '#4BB543',
  BORDER_COLOR: '#dbdbdb',
  DANGER_COLOR: 'tomato',
  MIDNIGHT: 'midnightblue',
  ROYAL: 'royalblue',
  DARK_COLOR: '#000',
  LIGHT_COLOR: '#fff',
  INFO_COLOR: '#0074d9',
  white5: '#fff5',
  black3: '#0003',
  black5: '#0005',
  black7: '#0007',
  black9: '#000a',
  whitea: '#fffa',
  transparent: '#0000',
  SEMI_DARK: '#111',
  Dark2: '#222',
};

export const customStyles = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: '#fe7013',
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: '#fe7013',
  stepStrokeUnFinishedColor: '#aaaaaa',
  separatorFinishedColor: '#fe7013',
  separatorUnFinishedColor: '#aaaaaa',
  stepIndicatorFinishedColor: '#fe7013',
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: '#ffffff',
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: '#fe7013',
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnFinishedColor: '#aaaaaa',
  labelColor: '#999999',
  labelSize: 13,
  currentStepLabelColor: '#fe7013',
};
